// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1tonO-F07wmwMH3VTxNIMP4ruUbrGDlQ',
    appId: '1:224782797768:web:88817cb2dc5baf1d9dcefd',
    messagingSenderId: '224782797768',
    projectId: 'funeral-menu',
    authDomain: 'funeral-menu.firebaseapp.com',
    databaseURL: 'https://funeral-menu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'funeral-menu.appspot.com',
    measurementId: 'G-DPKTJXDTXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC73uob6G01ljScuQdnVbC3ZrujdeY-gkI',
    appId: '1:224782797768:android:9207a4395c3761c39dcefd',
    messagingSenderId: '224782797768',
    projectId: 'funeral-menu',
    databaseURL: 'https://funeral-menu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'funeral-menu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtYHLf4VnSvuo-BQzArKAHG31ebl6ufyg',
    appId: '1:224782797768:ios:51293b51368e8c6c9dcefd',
    messagingSenderId: '224782797768',
    projectId: 'funeral-menu',
    databaseURL: 'https://funeral-menu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'funeral-menu.appspot.com',
    iosBundleId: 'com.example.funeralMenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtYHLf4VnSvuo-BQzArKAHG31ebl6ufyg',
    appId: '1:224782797768:ios:137713aa596b88b29dcefd',
    messagingSenderId: '224782797768',
    projectId: 'funeral-menu',
    databaseURL: 'https://funeral-menu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'funeral-menu.appspot.com',
    iosBundleId: 'com.example.funeralMenu.RunnerTests',
  );
}
